// app/layout.tsx
import './globals.css'
import Header from './components/Header'
import { Work_Sans } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'

const workSans = Work_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`flex flex-col min-h-screen bg-theme-blue-900 ${workSans.className}`}
        >
          {/* @ts-expect-error Server Component */}
          <Header />
          <main className="flex-1">{children}</main>
        </body>
      </html>
    </ClerkProvider>
  )
}
